name: Build code for windows version

on:
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install easygui
        pip install pymongo
        pip install elevate
        pip install sentry_sdk
        pip install webbrowser
    - name: Compile code
      run: |
        .\COMPILE.bat
